# Generated by Django 3.2.3 on 2021-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210524_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='desc',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
