# Generated by Django 3.2.3 on 2021-05-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads',
            name='content',
        ),
        migrations.AddField(
            model_name='threads',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.post', verbose_name='Посты'),
        ),
    ]
