# Generated by Django 3.2.3 on 2021-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_post_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='thid',
            field=models.IntegerField(null=True, verbose_name='Id темы'),
        ),
    ]
