# Generated by Django 3.2.3 on 2021-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210527_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(null=True, verbose_name='Лайки'),
        ),
    ]
