# Generated by Django 3.2.3 on 2021-05-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='icon',
            field=models.CharField(max_length=100, null=True, verbose_name='Иконка'),
        ),
    ]
