# Generated by Django 3.2.3 on 2021-05-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_fruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrUser',
        ),
    ]
