# Generated by Django 3.2.3 on 2021-05-30 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='com',
            field=models.BooleanField(default=False, verbose_name='Администратор форума?'),
        ),
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
