# Generated by Django 3.2.3 on 2021-05-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210530_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации'),
        ),
    ]
