# Generated by Django 3.2.3 on 2021-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_users_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='color',
            field=models.CharField(default='#58595B', max_length=20, verbose_name='HEX цвет ника'),
        ),
        migrations.AddField(
            model_name='users',
            name='discord',
            field=models.CharField(max_length=80, null=True, verbose_name='Дискорд пользователя'),
        ),
        migrations.AddField(
            model_name='users',
            name='stat',
            field=models.CharField(max_length=70, null=True, verbose_name='Статус пользователя'),
        ),
        migrations.AddField(
            model_name='users',
            name='telegram',
            field=models.CharField(max_length=80, null=True, verbose_name='Телеграмм пользователя'),
        ),
        migrations.AddField(
            model_name='users',
            name='vk',
            field=models.CharField(max_length=80, null=True, verbose_name='Вк пользователя'),
        ),
    ]
