# Generated by Django 3.2.3 on 2021-05-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210531_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, null=True, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='users',
            name='discord',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Дискорд пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Симпатии'),
        ),
        migrations.AlterField(
            model_name='users',
            name='stat',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Статус пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Телеграмм пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='vk',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Вк пользователя'),
        ),
    ]
