# Generated by Django 3.2.3 on 2021-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_threads_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
