# Generated by Django 3.2.3 on 2021-05-31 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Создатель темы'),
        ),
    ]
